#!/bin/bash

echo "🚀 GitHub Setup Commands"
echo "========================"
echo ""
echo "After creating your GitHub repository, run these commands:"
echo ""
echo "# Add your GitHub repository as remote origin"
echo "git remote add origin https://github.com/YOUR_USERNAME/meeting-intelligence-agent.git"
echo ""
echo "# Push your code to GitHub"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Replace YOUR_USERNAME with your actual GitHub username!"
echo ""
echo "Example:"
echo "git remote add origin https://github.com/johnsmith/meeting-intelligence-agent.git"
echo "git branch -M main"
echo "git push -u origin main"
