#!/bin/bash

echo "🚀 SIMPLE DEPLOYMENT GUIDE"
echo "========================="
echo ""

echo "📋 STEP 1: Deploy Backend to Railway"
echo "===================================="
echo "1. Go to https://railway.app"
echo "2. Sign up with GitHub (MalikAqsa-cloud)"
echo "3. Click 'New Project'"
echo "4. Select 'Deploy from GitHub repo'"
echo "5. Choose 'Meeting-Intelligent-Agent'"
echo "6. Railway will auto-detect Python"
echo "7. Wait for deployment (2-3 minutes)"
echo "8. Copy your Railway URL"
echo ""

echo "📋 STEP 2: Deploy Frontend to Netlify"
echo "====================================="
echo "1. Go to https://netlify.com"
echo "2. Sign up with GitHub (MalikAqsa-cloud)"
echo "3. Click 'New site from Git'"
echo "4. Choose 'Meeting-Intelligent-Agent'"
echo "5. Configure:"
echo "   - Base directory: frontend"
echo "   - Build command: npm run build"
echo "   - Publish directory: frontend/dist"
echo "6. Add environment variable:"
echo "   VITE_API_URL=https://your-railway-url.up.railway.app"
echo "7. Deploy!"
echo ""

echo "🎯 Your URLs will be:"
echo "- Frontend: https://your-app-name.netlify.app"
echo "- Backend: https://your-app-name.up.railway.app"
echo "- API Docs: https://your-backend-url.up.railway.app/docs"
echo ""

echo "✅ This approach is much simpler and more reliable!"
