version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TRELLO_API_KEY=${TRELLO_API_KEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
      - TRELLO_LIST_ID=${TRELLO_LIST_ID}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
